# Generated by Django 2.2.12 on 2022-04-30 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(choices=[('PR', 'Paraná'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('SC', 'Santa Catarina'), ('RO', 'Rondônia')], max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o seu nome completo', max_length=50, verbose_name='Qual seu nome?')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=100)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.Cidade')),
            ],
        ),
    ]
