# Generated by Django 4.0.4 on 2022-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(choices=[('PR', 'Paraná'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('SC', 'Santa Catarina'), ('RO', 'Rondônia')], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
