# Generated by Django 4.0.4 on 2022-05-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_cidade_estado_alter_cidade_id_alter_pessoa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
