# Generated by Django 4.0.4 on 2022-05-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='endereco_armazenamento',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='endereco_armazenamento',
            old_name='enderecoCompartilhado',
            new_name='endereco_compartilhado',
        ),
        migrations.RenameField(
            model_name='endereco_armazenamento_categoria',
            old_name='enderecoArmazenamento',
            new_name='endereco_armazenamento',
        ),
        migrations.RenameField(
            model_name='item_descartavel',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='item_descartavel',
            old_name='enderecoArmazenamento',
            new_name='endereco_armazenamento',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='dataCadastro',
            new_name='data_cadastro',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='dataNascimento',
            new_name='data_nascimento',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='endereco_armazenamento',
            name='numero',
            field=models.IntegerField(verbose_name='Nº'),
        ),
        migrations.AlterField(
            model_name='endereco_armazenamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='endereco_armazenamento',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='item_descartavel',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone 2'),
        ),
    ]
