# Generated by Django 4.0.4 on 2022-06-27 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_endereco_armazenamento_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_descartavel',
            name='perfil',
        ),
    ]
