# Generated by Django 4.0.4 on 2022-09-12 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0003_remove_item_descartavel_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='status',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone1',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='telefone2',
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(default='123', max_length=15, verbose_name='Telefone Celular'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
