# Generated by Django 4.0.4 on 2022-09-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_perfil_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco_armazenamento',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
